# Joints limits

limits:
  shoulder_pan:
    lower: -3.14159265359
    upper: 3.14159265359
    velocity: 2.16
    effort: 330.0
  shoulder_lift:
    lower: -3.14159265359
    upper: 3.14159265359
    velocity: 2.16
    effort: 330.0
  elbow_joint:
    lower: -3.14159265359
    upper: 3.14159265359
    velocity: 3.15
    effort: 150.0
  wrist_1:
    lower: -3.14159265359
    upper: 3.14159265359
    velocity: 3.2
    effort: 54.0
  wrist_2:
    lower: -3.14159265359
    upper: 3.14159265359
    velocity: 3.2
    effort: 54.0
  wrist_3:
    lower: -3.14159265359
    upper: 3.14159265359
    velocity: 3.2
    effort: 54.0

# Physical parameters

dh_parameters:
  d1: 0.1273
  a2: -0.612
  a3: -0.5723
  d4: 0.163941
  d5: 0.1157
  d6: 0.0922

offsets:
  shoulder_offset: 0.220941 # measured from model
  elbow_offset: -0.1719 # measured from model

inertia_parameters:
  base_mass: 4.0  # This mass might be incorrect
  shoulder_mass: 7.778
  upper_arm_mass: 12.93
  forearm_mass: 3.87
  wrist_1_mass: 1.96
  wrist_2_mass: 1.96
  wrist_3_mass: 0.202

  shoulder_radius: x0.060   # FROM UR5 DON'T USE
  upper_arm_radius: x0.054  # FROM UR5 DON'T USE
  elbow_radius: x0.060      # FROM UR5 DON'T USE
  forearm_radius: x0.040    # FROM UR5 DON'T USE
  wrist_radius: x0.045      # FROM UR5 DON'T USE

  links:
    base:
      radius: 0.075
      length: 0.038
    shoulder:
      radius: 0.075
      length: 0.178
    upperarm:
      radius: 0.075
      length: 0.612
    forearm:
      radius: 0.075
      length: 0.5723
    wrist_1:
      radius: 0.075
      length: 0.12
    wrist_2:
      radius: 0.075
      length: 0.12
    wrist_3:
      radius: 0.075
      length: 0.12

  center_of_mass:
    shoulder_cog:
      x: 0.0
      y: 0.00244
      z: -0.037
    upper_arm_cog:
      x: 0.00001
      y: 0.15061
      z: 0.38757
    forearm_cog:
      x: -0.00012
      y: 0.06112
      z: 0.1984
    wrist_1_cog:
      x: -0.00021
      y: -0.00112
      z: 0.02269
    wrist_2_cog:
      x: -0.00021
      y: 0.00112
      z: 0.002269
    wrist_3_cog:
      x: 0.0
      y: -0.001156
      z: -0.00149

mesh_files:
  base:
    visual:
      mesh: "package://ur_description/meshes/ur10/visual/base.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur10/collision/base.stl"

  shoulder:
    visual:
      mesh: "package://ur_description/meshes/ur10/visual/shoulder.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur10/collision/shoulder.stl"

  upper_arm:
    visual:
      mesh: "package://ur_description/meshes/ur10/visual/upperarm.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur10/collision/upperarm.stl"
      mesh_files:

  forearm:
    visual:
      mesh: "package://ur_description/meshes/ur10/visual/forearm.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur10/collision/forearm.stl"

  wrist_1:
    visual:
      mesh: "package://ur_description/meshes/ur10/visual/wrist1.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur10/collision/wrist1.stl"

  wrist_2:
    visual:
      mesh: "package://ur_description/meshes/ur10/visual/wrist2.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur10/collision/wrist2.stl"

  wrist_3:
    visual:
      mesh: "package://ur_description/meshes/ur10/visual/wrist3.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur10/collision/wrist3.stl"