# Joints limits

limits:
  shoulder_pan:
    lower: -3.14159265359
    upper: 3.14159265359
    velocity: 3.15
    effort: 150.0
  shoulder_lift:
    lower: -3.14159265359
    upper: 3.14159265359
    velocity: 3.15
    effort: 150.0
  elbow_joint:
    lower: -3.14159265359
    upper: 3.14159265359
    velocity: 3.15
    effort: 150.0
  wrist_1:
    lower: -3.14159265359
    upper: 3.14159265359
    velocity: 3.2
    effort: 28.0
  wrist_2:
    lower: -3.14159265359
    upper: 3.14159265359
    velocity: 3.2
    effort: 28.0
  wrist_3:
    lower: -3.14159265359
    upper: 3.14159265359
    velocity: 3.2
    effort: 28.0

# Physical parameters

dh_parameters:
  d1: 0.089159
  a2: -0.42500
  a3: -0.39225
  d4: 0.10915
  d5: 0.09465
  d6: 0.0823

offsets:
  shoulder_offset: 0.13585 # measured from model
  elbow_offset: -0.1197 # measured from model

inertia_parameters:
  base_mass: 4.0  # This mass might be incorrect
  shoulder_mass: 3.7000
  upper_arm_mass: 8.3930
  forearm_mass: 2.2750
  wrist_1_mass: 1.2190
  wrist_2_mass: 1.2190
  wrist_3_mass: 0.1879

  shoulder_radius: 0.060   # manually measured
  upper_arm_radius: 0.054  # manually measured
  elbow_radius: 0.060      # manually measured
  forearm_radius: 0.040    # manually measured
  wrist_radius: 0.045      # manually measured

  links:
    base:
      radius: 0.06
      length: 0.05
    shoulder:
      radius: 0.06
      length: 0.15
    upperarm:
      radius: 0.06
      length: 0.56
    forearm:
      radius: 0.06
      length: 0.5
    wrist_1:
      radius: 0.6
      length: 0.12
    wrist_2:
      radius: 0.6
      length: 0.12
    wrist_3:
      radius: 0.6
      length: 0.12

  center_of_mass:
    shoulder_cog:
      x: 0.0
      y: 0.00193
      z: -0.02561
    upper_arm_cog:
      x: 0.0
      y: -0.024201
      z: 0.2125
    forearm_cog:
      x: 0.0
      y: 0.0265
      z: 0.11993
    wrist_1_cog:
      x: 0.0
      y: 0.110949
      z: 0.01634
    wrist_2_cog:
      x: 0.0
      y: 0.0018
      z: 0.11099
    wrist_3_cog:
      x: 0.0
      y: 0.001159
      z: 0.0

mesh_files:
  base:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/base.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/base.stl"

  shoulder:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/shoulder.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/shoulder.stl"

  upper_arm:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/upperarm.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/upperarm.stl"
      mesh_files:

  forearm:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/forearm.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/forearm.stl"

  wrist_1:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/wrist1.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/wrist1.stl"

  wrist_2:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/wrist2.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/wrist2.stl"

  wrist_3:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/wrist3.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/wrist3.stl"