mesh_files:
  base:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/base.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/base.stl"

  shoulder:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/shoulder.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/shoulder.stl"

  upper_arm:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/upperarm.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/upperarm.stl"
      mesh_files:

  forearm:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/forearm.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/forearm.stl"

  wrist_1:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/wrist1.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/wrist1.stl"

  wrist_2:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/wrist2.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/wrist2.stl"

  wrist_3:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/wrist3.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/wrist3.stl"